version: '3'
services:
    backend:
        container_name: backend
        build: 
            context: .
            dockerfile: ./docker/images/backend/dockerfile
        volumes: 
            - ./:/app
        ports:
            - 3000:3000
            - 9229:9229